import type { Agent, Listing } from "./types";

/** Offline / missing-Supabase preview data for brand and layout review. */
export const MOCK_AGENTS: Agent[] = [
  {
    id: "a1",
    slug: "oracle-edge",
    name: "Oracle Edge",
    builder: { name: "0xForge Labs", builderScore: 92 },
    market: "Crypto",
    status: "live",
    description: "Cross-venue crypto prediction edges with tight risk caps.",
    agentScore: 94.8,
    winRate: 78,
    consistency: 0.86,
    maxDrawdown: -8.4,
    totalReturn: 42.8,
    rank: 1,
    traderCount: 128,
    listingFeeBps: 125,
    performanceFeeBps: 900,
    history: [0, 4, 7, 12, 18, 22, 28, 31, 36, 42.8],
    riskDefaults: { positionCapPct: 12, maxDrawdownPct: 15, autoPause: true },
  },
  {
    id: "a2",
    slug: "flash-signal",
    name: "Flash Signal",
    builder: { name: "Pulseworks", builderScore: 88 },
    market: "Sports",
    status: "live",
    description: "In-play sports markets with latency-aware sizing.",
    agentScore: 91.2,
    winRate: 71,
    consistency: 0.81,
    maxDrawdown: -11.2,
    totalReturn: 31.4,
    rank: 2,
    traderCount: 96,
    listingFeeBps: 125,
    performanceFeeBps: 900,
    history: [0, 3, 5, 9, 14, 17, 21, 24, 28, 31.4],
    riskDefaults: { positionCapPct: 10, maxDrawdownPct: 14, autoPause: true },
  },
  {
    id: "a3",
    slug: "sentinel",
    name: "Sentinel",
    builder: { name: "Northline", builderScore: 84 },
    market: "Politics",
    status: "live",
    description: "Macro-political event markets with drawdown brakes.",
    agentScore: 88.7,
    winRate: 69,
    consistency: 0.79,
    maxDrawdown: -9.1,
    totalReturn: 24.9,
    rank: 3,
    traderCount: 74,
    listingFeeBps: 125,
    performanceFeeBps: 900,
    history: [0, 2, 6, 8, 11, 15, 18, 20, 23, 24.9],
    riskDefaults: { positionCapPct: 10, maxDrawdownPct: 12, autoPause: true },
  },
  {
    id: "a4",
    slug: "market-pulse",
    name: "Market Pulse",
    builder: { name: "Tidepool", builderScore: 80 },
    market: "Crypto",
    status: "vetting",
    description: "Short-horizon crypto pulse with conservative caps.",
    agentScore: 0,
    winRate: 0,
    consistency: 0,
    maxDrawdown: 0,
    totalReturn: 0,
    rank: 0,
    traderCount: 0,
    listingFeeBps: 125,
    performanceFeeBps: 900,
    history: [],
    riskDefaults: { positionCapPct: 12, maxDrawdownPct: 16, autoPause: true },
  },
];

// Sample "my listings" data for the dashboard. Real listings require a
// backend that scopes rows to a connected wallet — not built yet, so this
// stays local/mock rather than reading from the (currently unreadable)
// `listings` table.
export const MOCK_LISTINGS: Listing[] = [
  {
    id: "l1",
    agentSlug: "oracle-edge",
    allocatedCapital: 5000,
    currentValue: 6140,
    pnlPct: 22.8,
    status: "active",
    positionCapPct: 12,
    maxDrawdownPct: 15,
    autoPause: true,
    listedAt: "2026-06-02",
  },
  {
    id: "l2",
    agentSlug: "market-pulse",
    allocatedCapital: 2500,
    currentValue: 2690,
    pnlPct: 7.6,
    status: "active",
    positionCapPct: 12,
    maxDrawdownPct: 16,
    autoPause: true,
    listedAt: "2026-06-18",
  },
  {
    id: "l3",
    agentSlug: "sentinel",
    allocatedCapital: 1500,
    currentValue: 1410,
    pnlPct: -6.0,
    status: "paused",
    positionCapPct: 10,
    maxDrawdownPct: 12,
    autoPause: true,
    listedAt: "2026-05-14",
  },
];
